### ISSUE TITLE
undefined method `sampleRequest'

### ISSUE THREAD

**Issue by mattwilliamson** [pglombardo/IRC2HipChat#4]
I'm on OSX Yosemite and installed fresh. I configured according to docs, except `bundle exec rake start` kept telling me the HIPCHAT env var wasn't set. So I ran manually like so:

    HIPCHAT_API_TOKEN=xxxx ruby irc2hipchat.rb

But now it joins the IRC room, but gets errors and doesn't show anything in the Hipchat room.

    [2015/01/23 14:39:07.966] !! [New thread] For #<Cinch::Handler @event=:channel pattern=#<Cinch::Pattern:0x007fab39a9b460 @prefix=nil, @pattern=//, @suffix=nil>>: #<Thread:0x007fab39a51a18> -- 1 in total.
    [2015/01/23 14:39:07.966] !! /Library/Ruby/Gems/2.0.0/gems/oboe-2.6.1.0/lib/oboe_metal.rb:86:in `sample?': undefined method `sampleRequest' for Oboe_metal::Context:Class (NoMethodError)
    [2015/01/23 14:39:07.966] !!    /Library/Ruby/Gems/2.0.0/gems/oboe-2.6.1.0/lib/oboe/api/logging.rb:71:in `log_start'
    [2015/01/23 14:39:07.967] !!    /Library/Ruby/Gems/2.0.0/gems/oboe-2.6.1.0/lib/oboe/api/tracing.rb:77:in `start_trace'
    [2015/01/23 14:39:07.967] !!    irc2hipchat.rb:28:in `block (2 levels) in <main>'
    [2015/01/23 14:39:07.967] !!    /Library/Ruby/Gems/2.0.0/gems/cinch-2.1.0/lib/cinch/handler.rb:97:in `instance_exec'
    [2015/01/23 14:39:07.967] !!    /Library/Ruby/Gems/2.0.0/gems/cinch-2.1.0/lib/cinch/handler.rb:97:in `block in call'
    [2015/01/23 14:39:07.967] !! [Thread done] For #<Cinch::Handler @event=:channel pattern=#<Cinch::Pattern:0x007fab39a9b460 @prefix=nil, @pattern=//, @suffix=nil>>: #<Thread:0x007fab39a51a18> -- 0 remaining.
    [2015/01/23 14:39:38.385] >> :matt!~matt@ool-4353a0e8.dyn.optonline.net PRIVMSG #acme :hmm, didn't work

**Comment by pglombardo** [comment]
Hi @mattwilliamson !  Thanks for letting me know.  That shouldn't be happening - one of the gems in the bundle doesn't act nice when under Mac OSX.

Give me a bit and I'll see if I can push up a fix.

**Comment by pglombardo** [comment]
Wow @mattwilliamson this issue completely fell off my radar.  My apologies.

I've updated the bundle.  This issue should no longer be an issue on OSX systems.

Thanks for being patient (for two months!).
